# Generated by Django 3.2.7 on 2021-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название изображения')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Изображения',
                'ordering': ['id'],
            },
        ),
    ]
